version: '3'

services:
  #php
  php:
    image: php:7.2.7-fpm-alpine
    container_name: php
    volumes:
      - ./public_html/:/public_html
    restart: always
    expose:
     - 9000
  #webserver (nginx)
  webserver:
    #image: nginx:stable
    image: scriptmedia/nginx:stable
    container_name: webserver
    volumes:
      - ./config/default/:/etc/nginx/conf.d/
      - ./public_html/:/public_html
    ports:
      - 80:80
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - NGINX_USER=admin
    depends_on:
      - php
  #db (mariadb)
  db:
    image: mariadb:10.4.7
    container_name: mariadb
    volumes:
      - ./data/db/mariadb:/var/lib/mysql/
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    expose:
      - 3306
